import "./globals.css";

export const metadata = {
  title: "High Taste Ceramics",
  description: "Generated by create next app",
  keywords: ["ceramics", "pottery", "home decor", "High Taste", "ceramic art"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
