import "../globals.css";
import "remixicon/fonts/remixicon.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "AI Web Audit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#374151",
              color: "#f9fafb",
              fontSize: "13px",
              padding: "12px 16px",
              borderRadius: "8px",
              boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
            },
            success: {
              duration: 3000,
              style: {
                background: "#065f46",
                color: "#ecfdf5",
              },
            },
            error: {
              duration: 5000,
              style: {
                background: "#7f1d1d",
                color: "#fef2f2",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
